### ISSUE TITLE
Query single direction in readExtinction.py

### ISSUE THREAD

**Issue by Thalos12** [willclarkson/rubinCadenceScratchWIC#14]
It would be useful to add a method to `ebv3d` for querying along one specific direction (full profile or single distance), at the moment we can only query the whole map at a single distance.

**Comment by willclarkson** [comment]
Hi @Thalos12 -  I think I’ve solved the issue you were reporting about **testGetOneSightline** reporting different E(B-V) from those suggested by **hybridSightline** . I think the difference was in the “pixFillFrac” argument used in **hybridSightline**, which was NOT 1.0 when I made the map in the first place. I’ve added lines to **testGetOneSightline** so that it prints header information from the imported fits file to screen, to make it easier to generate a sightline from **hybridSightline** that should match the extinction map. Based on tests, the values returned by the test routines do match those appearing along the sight-line, but I’d appreciate a second check! I added extensive comments to the beginning of **testGetOneSightline** which illustrate the steps that return consistent E(B-V) estimates on my system.

Also for what it’s worth: both **getEBVatSightline** and **testGetOneSightline** can accept scalar or vector l, b - so the user could send in all of their positions at once (and **getEBVatSightline** can also now optionally interpolate over the sphere to match those positions). 

(We probably should ensure that all the relevant keywords that would be sent to hybridSightline are propagated into the fits output in **loopSightlines** when the map is generated. With most of **compareExtinctions.py** still passing arguments back and forth between methods (rather than refactoring into instances of classes), that's going to be annoying but it should be straightforward. I think refactoring into OO form can wait until after the SCOC deadline! )

**Comment by Thalos12** [comment]
Thanks a lot for looking into the issue, the additional information returned by the **testGetOneSightline** is perfect for assuring I am doing the comparison right, as I had not considered the effect of the "pixFillFrac", than you for the explanation!!

It is great that l and b vectors can be used, this will speed up things a lot. The optional interpolation could also be quite useful.

Checking the keywords seems a good idea, maybe when the functions are in "verbose mode"?

**Comment by Thalos12** [comment]
Now the **getDeltaMag** and **getDistanceAtMag** methods of the **ebv3d** class accept an `ipix` argument, either a `float` or a `list` or a numpy 1D array, which determines which pixels to query (see #24 for more detail).

**Comment by Thalos12** [comment]
Closing issue because it is solved by pull request #24.
